name: Deployment

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*'
    tags-ignore:
      - v*
    types: [closed]

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: versioned-release
  cancel-in-progress: true

jobs:
    build-release:
        name: Build Release
        if: ${{ github.event.pull_request.merged && !startsWith(github.ref, 'refs/tags/') }}
        runs-on: windows-latest
        steps:
            - name: Install MSBuild Tools
              uses: microsoft/setup-msbuild@v1.1
              
            - name: Install NuGet
              uses: nuget/setup-nuget@v1
              with:
                nuget-api-key: ${{ secrets.NuGetAPIKey }}
                nuget-version: '5.x'
                
            - name: Checkout
              uses: actions/checkout@v3.0.2
              with:
                submodules: 'true'
                fetch-depth: 0
             
            # Required to find output module BHM without glob pattern.
            - name: Get module *.csproj name
              id: csproj
              working-directory: ./src
              run: Write-Output "::set-output name=name::$((Get-ChildItem $dir -File '*.csproj').Basename)"
            
            # Used as prefix in module BHM naming scheme.
            - name: Get manifest namespace
              id: namespace
              uses: notiz-dev/github-action-json-property@release
              with: 
                path: 'src/manifest.json'
                prop_path: 'namespace'

            - name: Get manifest version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with: 
                path: 'src/manifest.json'
                prop_path: 'version'
                
            # 'msbuild restore' does not support NuGet package.config format
            - name: Restore NuGet packages
              working-directory: ./src
              run: nuget restore
            
            - name: Build Solution
              working-directory: ./src
              run: msbuild -p:Configuration=Release -p:VERSIONED_BUILD=${{ steps.version.outputs.prop }}

            - name: Create Changelog
              id: changelog
              uses: TriPSs/conventional-changelog-action@v3.15.0
              with:
                skip-commit: 'true'
                output-file: 'false'
                skip-version-file: 'true'
                
            - name: Create Release
              uses: svenstaro/upload-release-action@2.3.0
              if: ${{ steps.changelog.outputs.skipped == 'false' }}
              with:
                repo_token: ${{ github.token }}
                # Using 'file_glob' disables 'asset_name' renaming.
                # We use the *.csproj name to workaround this.
                file_glob: 'false'
                file: src/bin/Release/${{ steps.csproj.outputs.name }}.bhm
                # Rename the module BHM to release naming scheme.
                asset_name: '${{ steps.namespace.outputs.prop }}-${{ steps.version.outputs.prop }}.bhm'
                overwrite: true
                tag: v${{ steps.version.outputs.prop }}
                prerelease: false
                body: ${{ steps.changelog.outputs.clean_changelog }}
