name: PR

on: [pull_request]

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Install MSBuild Tools
              uses: microsoft/setup-msbuild@v1.1
              
            - name: Install NuGet
              uses: nuget/setup-nuget@v1
              with:
                nuget-api-key: ${{ secrets.NuGetAPIKey }}
                nuget-version: '5.x'

            - name: Checkout
              uses: actions/checkout@v3.0.2
              with:
                submodules: 'true'
                fetch-depth: 0

            # 'msbuild restore' does not support NuGet package.config format
            - name: Run NuGet restore
              working-directory: ./src
              run: nuget restore
            
            - name: Run msbuild
              working-directory: ./src
              run: msbuild -p:Configuration=Release -p:VERSIONED_BUILD=${{ steps.gitversion.outputs.semVer }}

            # Required to find output module BHM without glob pattern.
            - name: Get module *.csproj name
              id: csproj
              working-directory: ./src
              run: Write-Output "::set-output name=name::$((Get-ChildItem $dir -File '*.csproj').Basename)"
            
            # Used as prefix in module BHM naming scheme.
            - name: Get manifest namespace
              id: namespace
              uses: notiz-dev/github-action-json-property@release
              with: 
                path: 'src/manifest.json'
                prop_path: 'namespace'
                
            - name: Upload BHM artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                name: '${{ steps.namespace.outputs.prop }}-${{ steps.gitversion.outputs.majorMinorPatch }}.bhm'
                path: src/bin/Release/${{ steps.csproj.outputs.name }}.bhm
